name: Semgrep

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  semgrep:
    name: semgrep/ci
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
    container:
      image: semgrep/semgrep
    if: (github.actor != 'dependabot[bot]')
    steps:
      - uses: actions/checkout@v4
      - run: |
          apk update
          apk add dotnet8-sdk
          semgrep ci --allow-local-builds --verbose --supply-chain # name: Semgrep Scans with .NET lock files